jobs:
  buildMinApi21:
    name: Build minApi21 debug APK
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      env:
        JSON_CONTENT: ${{ secrets.GOOGLE_SERVICES_JSON }}
      if: ${{ env.JSON_CONTENT != '' }}
      name: Set environmental variables
      run: 'printf ''GOOGLE_SERVICES_JSON<<EOF\n%s\nEOF\n'' "$JSON_CONTENT" >> $GITHUB_ENV

        '
      shell: bash
    - continue-on-error: true
      env:
        CRASH_REPORT_WEBHOOK_URL: ${{ secrets.CRASH_REPORT_WEBHOOK_URL }}
      name: Build debug APK
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleMinApi21Debug
    - continue-on-error: true
      name: Upload debug APK
      uses: actions/upload-artifact@v3
      with:
        name: apk-minApi21-debug
        path: app/build/outputs/apk/minApi21/debug
  buildMinApi26:
    name: Build minApi26 debug APK
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      env:
        JSON_CONTENT: ${{ secrets.GOOGLE_SERVICES_JSON }}
      if: ${{ env.JSON_CONTENT != '' }}
      name: Set environmental variables
      run: 'printf ''GOOGLE_SERVICES_JSON<<EOF\n%s\nEOF\n'' "$JSON_CONTENT" >> $GITHUB_ENV

        '
      shell: bash
    - continue-on-error: true
      env:
        CRASH_REPORT_WEBHOOK_URL: ${{ secrets.CRASH_REPORT_WEBHOOK_URL }}
      name: Build debug APK
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleMinApi26Debug
    - continue-on-error: true
      name: Upload debug APK
      uses: actions/upload-artifact@v3
      with:
        name: apk-minApi26-debug
        path: app/build/outputs/apk/minApi26/debug
name: Android CI
on:
  repository_dispatch:
    types: trigger-ga___android.yml
